[package]
name = "rubot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owner = "0.0.0"
serenity = "0.11.6"
